# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vllm_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vllm_protocol.proto\"J\n\x0cVLLMProtocol\x12\x15\n\routput_tokens\x18\x01 \x01(\x05\x12\x14\n\x0cinput_tokens\x18\x02 \x01(\x05\x12\r\n\x05texts\x18\x03 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vllm_protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VLLMPROTOCOL._serialized_start=23
  _VLLMPROTOCOL._serialized_end=97
# @@protoc_insertion_point(module_scope)
